// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjw8VII8u9KROKIq7apqU6zu_VeJQL6eE',
    appId: '1:649628176251:web:c0b1d104304a8a5851f7de',
    messagingSenderId: '649628176251',
    projectId: 'foodpanda-app-a740f',
    authDomain: 'foodpanda-app-a740f.firebaseapp.com',
    storageBucket: 'foodpanda-app-a740f.firebasestorage.app',
    measurementId: 'G-LVQ3CFZYQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSHSoRb03lZuxBC_p7r-1QnL-mx6B7REc',
    appId: '1:649628176251:android:b0c7f041a1c92fa251f7de',
    messagingSenderId: '649628176251',
    projectId: 'foodpanda-app-a740f',
    storageBucket: 'foodpanda-app-a740f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCR1fw4JkD1q4qWGwK8APKpv--7AuYgiM',
    appId: '1:649628176251:ios:87cbf91f733c4f3551f7de',
    messagingSenderId: '649628176251',
    projectId: 'foodpanda-app-a740f',
    storageBucket: 'foodpanda-app-a740f.firebasestorage.app',
    iosBundleId: 'com.example.shoppingCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCR1fw4JkD1q4qWGwK8APKpv--7AuYgiM',
    appId: '1:649628176251:ios:87cbf91f733c4f3551f7de',
    messagingSenderId: '649628176251',
    projectId: 'foodpanda-app-a740f',
    storageBucket: 'foodpanda-app-a740f.firebasestorage.app',
    iosBundleId: 'com.example.shoppingCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjw8VII8u9KROKIq7apqU6zu_VeJQL6eE',
    appId: '1:649628176251:web:8e0c4523d36c283751f7de',
    messagingSenderId: '649628176251',
    projectId: 'foodpanda-app-a740f',
    authDomain: 'foodpanda-app-a740f.firebaseapp.com',
    storageBucket: 'foodpanda-app-a740f.firebasestorage.app',
    measurementId: 'G-HT68BFX093',
  );

}